PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX base: <http://llama.mshri.on.ca/lore-base.owl#>
PREFIX pheno: <http://llama.mshri.on.ca/lore-phenotype.owl#>
PREFIX genome: <http://llama.mshri.on.ca/lore-genome.owl#>
PREFIX mol: <http://llama.mshri.on.ca/lore-molecules.owl#>
PREFIX ia: <http://llama.mshri.on.ca/lore-interaction.owl#>

SELECT ?entrez ?mut (COUNT(DISTINCT ?posIA) AS ?numMaintain) (COUNT(DISTINCT ?negIA) AS ?numInterrupt)
WHERE {
	?allele rdf:type genome:Allele.
	OPTIONAL {?allele ia:affectsPositively ?posIA.}
	OPTIONAL {?allele ia:affectsNegatively ?negIA.}

	?allele ^genome:hasAllele/base:hasXRef ?geneXRef.
	?geneXRef base:hasAuthority <urn:lore:Authority#EntrezGene>;
		base:hasValue ?entrez.
	?allele genome:hasMutation ?mut.
} 
GROUP BY ?entrez ?mut
ORDER BY ?entrez ?mut